spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:logback-spring.xml
  path: ~/logs/push-wechat

wx:
  verifyFile: nPamSDXCVOlXvM6C