spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:logback-spring.xml
  path: ~/logs/push-wechat

wx:
  verifyFile: nPamSDXCVOlXvM6C

tuling:
  apiKey: 92abc57cc89f487189e7b6e26de8d6b6
  secret: 78246b95781084d3
  url: http://openapi.tuling123.com/openapi/api/v2